### ISSUE TITLE
maybe a sizing bot?

### ISSUE THREAD

**Issue by monkeypants** [bugflow/kanned-bananas#1]
imagine we have a sizing bot.

each day, it gets a list of unsized tickets from the backlog (and some of the other columns) and sorts them in priority order.

Then, for each ticket (starting with highest priority then decending), if a particular developer has not sized it, then ask them in a PM about it (conversational bot, post link to ticket and say "you developer my fine fellow, what size do you think this tieckt size is?"). When all developers have sized it, it posts in group channel "we have a size for #xxx: 3!" (and does the zenhub sizing). So developers get nagged once per day to size the top priority unsized ticket, and as soon as they size it they get nagged about the next top priority (etc) until all tickets are sized. They never get nagged about sized tickets (by them, or as a finalized size).

If a ticket sizing is incomplete but the DM wants to push a size through, they (somehow) review the partial sizings and then just manually push a size onto it.

If that's not kanned-bananas then when we have a new repo (sizebot) we can move this ticket there. And edit it (remove this comment)

**Comment by monkeypants** [comment]
https://rasa.com

**Comment by dormerod** [comment]
This should probably be another project when we get time.

Move vote for the project name: `hypothesize` :smile:

**Comment by monkeypants** [comment]
https://github.com/bugflow/hypothesize
