### ISSUE TITLE
stocks ticket summary

### ISSUE THREAD

**Issue by dormerod** [bugflow/kanned-bananas#24]
We might also want to add a ticket summary for the stocks report (similar to the one we have for the flows report. For example:
```
Summary (number of tickets):
  Product backlog: 47
  Sprint backlog: 8
  To be fixed: 1
  In progress: 3
  Testing: 5
```

@monkeypants, what do you think about this? Also, I'm thinking we drop the original idea of replicating the board in a spreadsheet. Not because we can't do it, just because I think the text summary is better. Do you agree?

_Originally posted by @dormerod in https://github.com/bugflow/kanned-bananas/issues/2#issuecomment-632420953_

**Comment by monkeypants** [comment]
Yes, this is a feature I want :)

text format is better for me. I think maybe a spreadsheet would be useful for people who like that sort of thing. When we meet one of those, we can ask them.
