### ISSUE TITLE
implement Github GraphQL API to get issue titles etc

### ISSUE THREAD

**Issue by dormerod** [bugflow/kanned-bananas#4]
```
as a reader of the daily/weekly/monthly reports
I need issue/epic names and other human-readable information
so that I can understand what the report is talking about
```

So, it turns out that the [Zenhub Issues API](https://github.com/ZenHubIO/API#get-issue-data), in its wisdom, doesn't provide issue names/titles in its issue data responses.

We'll have to use the Github API and make at least one extra request to present all the information we need in the reports.

**Comment by dormerod** [comment]
@monkeypants, any other metadata you want to get (for future features) while we're doing this?

https://developer.github.com/v4/object/issue/#fields

**Comment by monkeypants** [comment]
http://c2.com/xp/YouArentGonnaNeedIt.html

**Comment by dormerod** [comment]
haha, ok then :)
